name: example-site
services:
  build:
    build: .
    volumes:
      - "./vault:/src/vault"
      - "./content:/src/content"
    develop:
      watch:
        - action: rebuild
          path: ./vault

  hugo:
    image: hugomods/hugo:exts-non-root
    command: server --buildDrafts --renderToMemory --poll 1000ms --disableFastRender
    volumes:
      - ".:/src/"
    ports: 
        - "8080:1313"
